# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 00:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170730_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporter',
            name='age',
        ),
    ]
